---
title: "tRNA count"
author: "Dmytro Strunin"
date: "12/23/2020"
output: html_document
---

```{r setup, include=FALSE, echo = FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(data.table)
library(magrittr)
library(factoextra)
```

## Read data

```{r message = F, warning = F}
PATH <- list.files('./dat/tmp/', full.names = T)

dat <- rbindlist(
  lapply(
    PATH,
    function(path) {
      message('Preprocessing file ', path)
      read_table(path, col_names = F) %>%
        select(-1) %>%
        separate(X3, into = c('tRNA', 'codone'), sep = '\\(') %>%
        rename('n' = X2) %>%
        mutate(
          codone = gsub('\\)$', '', codone),
          aa     = gsub('^tRNA-', '', tRNA),
          strain = str_trim(gsub('^([[:alnum:]]+)_{1}.+', '\\1', basename(path)))
        ) %>%
        select(aa, codone, n, strain) %>%
        distinct()
    }
    )
  )
```

# Preprocess data

```{r}
# strains to remove 

rmstr <- c('HH15275', 'CF609', 'MHH15275')

rmstr <- c(rmstr, dat$strain[grep('^Env|Ref.+$', dat$strain)])

dat %<>%
  mutate(
    aa     = factor(aa, levels = sort(unique(aa)), ordered = TRUE),
    codone = factor(
      codone,
      levels  = arrange(., aa, codone) %>% distinct() %>% pull(codone) %>% unique, 
      ordered = TRUE
      )
    ) %>%
  group_by(strain) %>%
  mutate(
    n = n / sum(n)
    ) %>%
  ungroup() %>%
  # HH15275 is outlayer remove
  filter(! (strain %in% rmstr))

groups <- dat$aa

mat <- dat %>%
  select(codone, n, strain) %>%
  group_by(strain, codone) %>%
  #summarize(n = first(n)) %>%
  pivot_wider(names_from = codone, values_from = n, values_fill = 0, values_fn = {median}) %>%
  column_to_rownames('strain') %>%
  as.matrix
  
```

# PCA

```{r}
pca <- prcomp(mat, scale = F, center = T)
fviz_eig(pca)
```

```{r}
fviz_pca_ind(pca,
             addEllipses = T,
             ellipse.type = 'confidence',
             #gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = F     # Avoid text overlapping
             )
```
```{r}
write_rds(dat, './dat/trna_codon_count_clean_long.Rds')
write_rds(mat, './dat/trna_codon_count_clean_wide.Rds')
```

```{r}
dst <- get_dist(mat, method = 'pearson', stand = FALSE)
hc <- hclust(dst)
plot(hc)
```

