---
title: "Align and graph tRNAs"
author: "Dmytro Strunin"
date: "4/16/2021"
output: html_document
---

```{r setup, include = FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(Biostrings)
library(msa)
```

## Reading the sequences

Read fasta files produced by `tRNAscan-SE`.

- Name the sequences as e.g. `Ala (GGC) (GGC) (+)`;
- Add metadata with variables `rna`, `antCodone`, `strand`, `strain`;

```{r}
PATH <- list.files('../../dat/out/trs/fasta/', full.names = TRUE)

names(PATH) <- gsub('.fa', '', basename(PATH))

not_empty <- names(PATH)[sapply(PATH, file.size) != 0]

PATH <- PATH[not_empty]

seqlst <- lapply(PATH, readDNAStringSet)

seqlst <- lapply(
   names(seqlst),
   function(i) {
      
     names(seqlst[[i]]) <- gsub(
       '^.+\\(([ +-])\\)\\s*([[:alpha:]]{3,5})\\s\\(([[:alpha:]]{3})\\).*$', 
       '\\2 \\3', 
       names(seqlst[[i]])
       )
     
     seqs_tmp <- unique(seqlst[[i]])
     
     meta <- data.frame(strain = i, tmp = names(seqlst[[i]])) %>%
        separate(tmp, into = c('trna', 'anticodone'), sep = '\\s') %>%
        mutate(name = names(seqlst[[i]])) %>%
        count(name, strain, trna, anticodone) %>%
        right_join(
           data.frame(name = names(seqs_tmp)), 
           by = 'name'
        )
        
     seqs_tmp <- unique(seqlst[[i]])
     metadata(seqs_tmp) <- meta
     seqs_tmp
   }
)

seqmeta <- do.call(rbind, lapply(seqlst, metadata))

names(seqlst) <- NULL

seqs <- do.call(c, seqlst)

metadata(seqs) <- seqmeta

names(seqs) <- metadata(seqs) %>%
   transmute(
      name = paste(strain, trna, anticodone)
   ) %>%
   pull(name)

seqs_split <- split(
   seqs, 
   f = paste(metadata(seqs)$trna, metadata(seqs)$anticodone, sep = '-')
)

alignments <- lapply(seqs_split, msa, method = 'ClustalOmega')
```

## Viewing the results

```{r}
msaPrettyPrint(
   alignments[["Pro-CGG"]], 
   output = "asis", 
   subset = c(1:25),
   logoColors = "rasmol",
   shadingColors = 'blues',
   showNames = "left", 
   showLogo = "top", 
   showLegend =  FALSE,
   askForOverwrite = FALSE, 
   verbose = FALSE, 
   file = "undet_whole_align.pdf"
)
```

